name: Build executables

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build executables

    strategy:
      matrix:
        runs-on: ['ubuntu-22.04', 'macos-14', 'macos-14-large', 'windows-2022']
    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --windowed --onefile antenati_gui.py

    - name: Upload artifact for Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: antenati_gui_windows.exe
        path: dist/antenati_gui.exe

    - name: Upload artifact for macOS and Ubuntu
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: antenati_gui_${{ matrix.runs-on }}
        path: dist/antenati_gui
