name: Python application

on: [push]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        runs-on: ['ubuntu-20.04', 'macos-12', 'windows-2019']

    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download test
      run: |
        python antenati.py "https://www.antenati.san.beniculturali.it/ark:/12657/an_ua19944535/w9DWR8x"
